### ISSUE TITLE
Update j2objc to 1.0.0

### ISSUE THREAD

**Issue by zasadnyy** [j2objc-contrib/j2objc-gradle#595]
Since j2objc 1.0.0 was released gradle plugin dependency requirement should be upgraded as well.

https://github.com/google/j2objc/releases/tag/1.0.0

**Comment by brunobowden** [comment]
This is definitely an issue... there's a number of changes in the 1.0.0 release that we'll need to make changes for.

**Comment by adil-hussain-84** [comment]
So I can't use the J2ObjC Gradle plugin right now with J2ObjC version 1.0.0? The [README](https://github.com/j2objc-contrib/j2objc-gradle/blob/master/README.md) should be updated then because it says "J2ObjC 0.9.8.2.1 or higher" for minimum requirements of the plugin.

**Comment by brunobowden** [comment]
I'm busy at a conference this week. I will update it come Feb 21. If anyone
can send a PR in the interim, I will review and approve it.

**Comment by adil-hussain-84** [comment]
Hey Bruno, I've created the pull request here:
https://github.com/j2objc-contrib/j2objc-gradle/pull/598

**Comment by efirestone** [comment]
Any updates on this? We'd love to have the latest 1.0.X features without having to manually implement the build process.

**Comment by brunobowden** [comment]
My apologies as I've been busy at TED and other events. I will look at this
tomorrow.

**Comment by efirestone** [comment]
No big deal actually. Working around this using `skipJ2objcVerification true` for now and everything seems ok.

**Comment by adil-hussain-84** [comment]
@efirestone I can't see how you got this working. I have a simple `SharedCode` module that imports some classes from the Guava library and makes use of them. This works and builds with the 0.9.8.2.1 release of the J2ObjC library. However, when I try build it with the 1.0.0 release I get errors of the following nature:

```
/Users/Adil/Library/J2ObjC/j2objc-1.0.0/include/J2ObjC_header.h:25:17: error: cannot create __weak reference in file using manual reference counting
id JreStrAppend(__weak id *lhs, const char *types, ...);
```

Did you encounter any such errors and, if so, how did you overcome them?

**Comment by adil-hussain-84** [comment]
Turns out this has been fixed in the 1.0.1 release of the J2ObjC library and all occurrences of `__weak` and have been replaced with `__unsafe_unretained`. Still curious to know how you got it to work @efirestone...

**Comment by efirestone** [comment]
We're not using Guava, so that's likely the difference. JRE core in 1.0.1 and 1.0.2 seem to work without issues.

**Comment by halfhp** [comment]
It's been a while...any movement on this one?

**Comment by mithepner** [comment]
Looks like there's an open pull request to upgrade to 1.0.2 https://github.com/j2objc-contrib/j2objc-gradle/pull/618

**Comment by BendroidFonk** [comment]
Any news on this?
